### PR TITLE
#75: Fix SSODOMAIN env var

### LINKED ISSUE #75: "-e SSODOMAIN" not working nicely on "domain": "example.com" in lmConf-1.json
```
sed -i "s/\.example\.com/\.${SSODOMAIN}/" /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.json /etc/nginx/sites-enabled/*
```
is not working on line
```
   "domain" : "example.com",
```
in /var/lib/lemonldap-ng/conf/lmConf-1.json

I fixed it using 
```
sed -i "s/example\.com/${SSODOMAIN}/" ...
```

### PR DESCRIPTION
**Pull request by abpai94**
Closes #75

### CODE REVIEW

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -42,7 +42,7 @@ if [ ! -z ${PROXY_RANGE+x} ]; then
     sed -i -e "s#.*real_ip_header.*#  real_ip_header    X-Forwarded-For;#g" /etc/nginx/sites-enabled/*
 fi
 
-sed -i "s/\.example\.com/\.${SSODOMAIN}/" /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.json /etc/nginx/sites-enabled/*
+sed -i "s/.example.com/.${SSODOMAIN}/" /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.json /etc/nginx/sites-enabled/*
```
Comment (coudot) [inline docker-entrypoint.sh]: This regexp could match "aexampleacom", this is not what we want.

The solution was given by @prigaux in the issue:
```
sed -i "s/example\.com/${SSODOMAIN}/" ...
```

**Review by coudot — CHANGES_REQUESTED** [review]

**Comment by abpai94** [comment]
@coudot apologies, I miss understood the issue. I have corrected it.

It appears the following works just as well.
```
sed -i "s/example.com/${SSODOMAIN}/"

**Comment by abpai94** [comment]
I have added the slash @coudot thanks for reminding me about the importance of the `.` representing a wildcard in regex.
